# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "nvme"
    "mpt3sas"
    "xhci_pci"
    "ahci"
    "uas"
    "usbhid"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "scheelite-root/local/root";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/nix" = {
    device = "scheelite-root/local/nix";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/home" = {
    device = "scheelite-root/safe/home";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/persist" = {
    device = "scheelite-root/safe/persist";
    fsType = "zfs";
    options = [ "zfsutil" ];
  };

  fileSystems."/boot" = {
    device = "/dev/nvme0n1p1";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  # fileSystems."/tank0" =
  #   { device = "scheelite-tank0/tank0";
  #     fsType = "zfs";
  #   };

  # fileSystems."/tank0/video" =
  #   { device = "scheelite-tank0/tank0/video";
  #     fsType = "zfs";
  #   };

  # fileSystems."/tank0/audio" =
  #   { device = "scheelite-tank0/tank0/audio";
  #     fsType = "zfs";
  #   };

  # fileSystems."/tank0/images" =
  #   { device = "scheelite-tank0/tank0/images";
  #     fsType = "zfs";
  #   };

  # fileSystems."/tank0/bulk" =
  #   { device = "scheelite-tank0/tank0/bulk";
  #     fsType = "zfs";
  #   };

  swapDevices = [
    { device = "/dev/disk/by-uuid/aeac891e-6a44-4937-8a6d-f7df60d3442c"; }
    { device = "/dev/nvme1n1p3"; }
  ];

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.eno1.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp10s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
